//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Mon Oct 28 21:39:44 IST 2024
//
//
// Ports:
// Name                         I/O  size props
// getResult                      O    33
// RDY_getResult                  O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// getResult_a                    I     8
// getResult_b                    I     8
// getResult_c                    I    32
//
// Combinational paths from inputs to outputs:
//   (getResult_a, getResult_b, getResult_c) -> getResult
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mac_wrap(CLK,
		RST_N,

		getResult_a,
		getResult_b,
		getResult_c,
		getResult,
		RDY_getResult);
  input  CLK;
  input  RST_N;

  // value method getResult
  input  [7 : 0] getResult_a;
  input  [7 : 0] getResult_b;
  input  [31 : 0] getResult_c;
  output [32 : 0] getResult;
  output RDY_getResult;

  // signals for module outputs
  wire [32 : 0] getResult;
  wire RDY_getResult;

  // remaining internal signals
  wire [32 : 0] IF_SEXT_IF_getResult_b_BIT_0_THEN_getResult_a__ETC__q17;
  wire [31 : 0] IF_SEXT_IF_getResult_b_BIT_0_THEN_getResult_a__ETC__q18,
		SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378,
		_theResult___fst__h65;
  wire [29 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d618;
  wire [27 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d617;
  wire [25 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d616;
  wire [23 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d615;
  wire [21 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d614;
  wire [19 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d613;
  wire [17 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d612;
  wire [15 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d611,
		x__h1092;
  wire [13 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d610;
  wire [11 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d609;
  wire [9 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d608;
  wire [8 : 0] IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q1,
	       IF_a046_AND_IF_getResult_b_BIT_6_40_THEN_getRe_ETC__q6,
	       IF_a390_AND_IF_getResult_b_BIT_3_6_THEN_getRes_ETC__q3,
	       IF_a494_AND_IF_getResult_b_BIT_5_92_THEN_getRe_ETC__q5,
	       IF_a598_AND_IF_getResult_b_BIT_7_88_THEN_getRe_ETC__q7,
	       IF_a838_AND_IF_getResult_b_BIT_2_8_THEN_getRes_ETC__q2,
	       IF_a942_AND_IF_getResult_b_BIT_4_44_THEN_getRe_ETC__q4;
  wire [7 : 0] IF_IF_IF_getResult_b_BIT_0_THEN_getResult_a_EL_ETC__q12,
	       IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q10,
	       IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q11,
	       IF_a046_XOR_IF_getResult_b_BIT_6_40_THEN_getRe_ETC__q16,
	       IF_a390_XOR_IF_getResult_b_BIT_3_6_THEN_getRes_ETC__q8,
	       IF_a494_XOR_IF_getResult_b_BIT_5_92_THEN_getRe_ETC__q13,
	       IF_a598_XOR_IF_getResult_b_BIT_7_88_THEN_getRe_ETC__q15,
	       IF_a838_XOR_IF_getResult_b_BIT_2_8_THEN_getRes_ETC__q9,
	       IF_a942_XOR_IF_getResult_b_BIT_4_44_THEN_getRe_ETC__q14,
	       IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2,
	       IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5,
	       IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49,
	       IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97,
	       IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145,
	       IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193,
	       IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241,
	       IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d607,
	       _theResult___fst__h1098,
	       _theResult___snd__h1099;
  wire [6 : 0] sum_BITS_7_TO_1___h18748;
  wire [5 : 0] IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC___d375,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d606;
  wire [4 : 0] IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0_B_ETC___d344;
  wire [3 : 0] IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC___d374,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d605;
  wire [2 : 0] IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0_B_ETC___d343;
  wire [1 : 0] SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d604;
  wire a__h10139,
       a__h10299,
       a__h10458,
       a__h10617,
       a__h10776,
       a__h10935,
       a__h11094,
       a__h11890,
       a__h12050,
       a__h12209,
       a__h12368,
       a__h12527,
       a__h12686,
       a__h12845,
       a__h13641,
       a__h13801,
       a__h13960,
       a__h14119,
       a__h14278,
       a__h14437,
       a__h14596,
       a__h15392,
       a__h15552,
       a__h15711,
       a__h15870,
       a__h1598,
       a__h16029,
       a__h16188,
       a__h16347,
       a__h17143,
       a__h17303,
       a__h17462,
       a__h17621,
       a__h17780,
       a__h17939,
       a__h18098,
       a__h2046,
       a__h2494,
       a__h2942,
       a__h3390,
       a__h3838,
       a__h8388,
       a__h8548,
       a__h8707,
       a__h8866,
       a__h9025,
       a__h9184,
       a__h9343,
       c__h10301,
       c__h10460,
       c__h10619,
       c__h10778,
       c__h10937,
       c__h11096,
       c__h12052,
       c__h12211,
       c__h12370,
       c__h12529,
       c__h12688,
       c__h12847,
       c__h13803,
       c__h13962,
       c__h14121,
       c__h14280,
       c__h14439,
       c__h14598,
       c__h15554,
       c__h15713,
       c__h15872,
       c__h16031,
       c__h16190,
       c__h16349,
       c__h17305,
       c__h17464,
       c__h17623,
       c__h17782,
       c__h17941,
       c__h18100,
       c__h19516,
       c__h19674,
       c__h19832,
       c__h19990,
       c__h20148,
       c__h20306,
       c__h20464,
       c__h20622,
       c__h20780,
       c__h20938,
       c__h21096,
       c__h21254,
       c__h21412,
       c__h21570,
       c__h21728,
       c__h21886,
       c__h22044,
       c__h22202,
       c__h22360,
       c__h22518,
       c__h22676,
       c__h22834,
       c__h22992,
       c__h23150,
       c__h23308,
       c__h23466,
       c__h23624,
       c__h23782,
       c__h23940,
       c__h24098,
       c__h6799,
       c__h6958,
       c__h7117,
       c__h7276,
       c__h7435,
       c__h7594,
       c__h8550,
       c__h8709,
       c__h8868,
       c__h9027,
       c__h9186,
       c__h9345,
       temp__h10142,
       temp__h10302,
       temp__h10461,
       temp__h10620,
       temp__h10779,
       temp__h10938,
       temp__h11097,
       temp__h11893,
       temp__h12053,
       temp__h12212,
       temp__h12371,
       temp__h12530,
       temp__h12689,
       temp__h12848,
       temp__h13644,
       temp__h13804,
       temp__h13963,
       temp__h14122,
       temp__h14281,
       temp__h14440,
       temp__h14599,
       temp__h15395,
       temp__h15555,
       temp__h15714,
       temp__h15873,
       temp__h16032,
       temp__h16191,
       temp__h16350,
       temp__h17146,
       temp__h17306,
       temp__h17465,
       temp__h17624,
       temp__h17783,
       temp__h17942,
       temp__h18101,
       temp__h19358,
       temp__h19517,
       temp__h19675,
       temp__h19833,
       temp__h19991,
       temp__h20149,
       temp__h20307,
       temp__h20465,
       temp__h20623,
       temp__h20781,
       temp__h20939,
       temp__h21097,
       temp__h21255,
       temp__h21413,
       temp__h21571,
       temp__h21729,
       temp__h21887,
       temp__h22045,
       temp__h22203,
       temp__h22361,
       temp__h22519,
       temp__h22677,
       temp__h22835,
       temp__h22993,
       temp__h23151,
       temp__h23309,
       temp__h23467,
       temp__h23625,
       temp__h23783,
       temp__h23941,
       temp__h24099,
       temp__h6640,
       temp__h6800,
       temp__h6959,
       temp__h7118,
       temp__h7277,
       temp__h7436,
       temp__h8391,
       temp__h8551,
       temp__h8710,
       temp__h8869,
       temp__h9028,
       temp__h9187,
       temp__h9346,
       x__h10156,
       x__h10316,
       x__h10475,
       x__h10634,
       x__h10793,
       x__h10952,
       x__h11111,
       x__h11907,
       x__h12067,
       x__h12226,
       x__h12385,
       x__h12544,
       x__h12703,
       x__h12862,
       x__h13658,
       x__h13818,
       x__h13977,
       x__h14136,
       x__h14295,
       x__h14454,
       x__h14613,
       x__h15409,
       x__h15569,
       x__h15728,
       x__h15887,
       x__h16046,
       x__h16205,
       x__h16364,
       x__h17160,
       x__h17320,
       x__h17479,
       x__h17638,
       x__h17797,
       x__h17956,
       x__h18115,
       x__h19372,
       x__h19531,
       x__h19689,
       x__h19847,
       x__h20005,
       x__h20163,
       x__h20321,
       x__h20479,
       x__h20637,
       x__h20795,
       x__h20953,
       x__h21111,
       x__h21269,
       x__h21427,
       x__h21585,
       x__h21743,
       x__h21901,
       x__h22059,
       x__h22217,
       x__h22375,
       x__h22533,
       x__h22691,
       x__h22849,
       x__h23007,
       x__h23165,
       x__h23323,
       x__h23481,
       x__h23639,
       x__h23797,
       x__h23955,
       x__h24113,
       x__h6654,
       x__h6814,
       x__h6973,
       x__h7132,
       x__h7291,
       x__h7450,
       x__h8405,
       x__h8565,
       x__h8724,
       x__h8883,
       x__h9042,
       x__h9201,
       x__h9360,
       y__h10157,
       y__h10317,
       y__h10476,
       y__h10635,
       y__h10794,
       y__h10953,
       y__h11112,
       y__h11908,
       y__h12068,
       y__h12227,
       y__h12386,
       y__h12545,
       y__h12704,
       y__h12863,
       y__h13659,
       y__h13819,
       y__h13978,
       y__h14137,
       y__h14296,
       y__h14455,
       y__h14614,
       y__h15410,
       y__h15570,
       y__h15729,
       y__h15888,
       y__h16047,
       y__h16206,
       y__h16365,
       y__h17161,
       y__h17321,
       y__h17480,
       y__h17639,
       y__h17798,
       y__h17957,
       y__h18116,
       y__h19373,
       y__h19532,
       y__h19690,
       y__h19848,
       y__h20006,
       y__h20164,
       y__h20322,
       y__h20480,
       y__h20638,
       y__h20796,
       y__h20954,
       y__h21112,
       y__h21270,
       y__h21428,
       y__h21586,
       y__h21744,
       y__h21902,
       y__h22060,
       y__h22218,
       y__h22376,
       y__h22534,
       y__h22692,
       y__h22850,
       y__h23008,
       y__h23166,
       y__h23324,
       y__h23482,
       y__h23640,
       y__h23798,
       y__h23956,
       y__h24114,
       y__h6655,
       y__h6815,
       y__h6974,
       y__h7133,
       y__h7292,
       y__h7451,
       y__h8406,
       y__h8566,
       y__h8725,
       y__h8884,
       y__h9043,
       y__h9202,
       y__h9361;

  // value method getResult
  assign getResult = { x__h24113 | y__h24114, _theResult___fst__h65 } ;
  assign RDY_getResult = 1'd1 ;

  // remaining internal signals
  assign IF_IF_IF_getResult_b_BIT_0_THEN_getResult_a_EL_ETC__q12 =
	     IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q11[0] ?
	       8'd1 :
	       8'd0 ;
  assign IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC___d374 =
	     { IF_a390_XOR_IF_getResult_b_BIT_3_6_THEN_getRes_ETC__q8[0],
	       IF_a838_XOR_IF_getResult_b_BIT_2_8_THEN_getRes_ETC__q9[0],
	       IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q10[0],
	       IF_IF_IF_getResult_b_BIT_0_THEN_getResult_a_EL_ETC__q12[0] } ;
  assign IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC___d375 =
	     { IF_a494_XOR_IF_getResult_b_BIT_5_92_THEN_getRe_ETC__q13[0],
	       IF_a942_XOR_IF_getResult_b_BIT_4_44_THEN_getRe_ETC__q14[0],
	       IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC___d374 } ;
  assign IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q1 =
	     (IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[1] &
	      IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[0]) ?
	       9'd2 :
	       9'd0 ;
  assign IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q10 =
	     (IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[1] ^
	      IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[0]) ?
	       8'd1 :
	       8'd0 ;
  assign IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q11 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[0] ?
	       8'd1 :
	       8'd0 ;
  assign IF_SEXT_IF_getResult_b_BIT_0_THEN_getResult_a__ETC__q17 =
	     (SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[0] &
	      getResult_c[0]) ?
	       33'd2 :
	       33'd0 ;
  assign IF_SEXT_IF_getResult_b_BIT_0_THEN_getResult_a__ETC__q18 =
	     (SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[0] ^
	      getResult_c[0]) ?
	       32'd1 :
	       32'd0 ;
  assign IF_a046_AND_IF_getResult_b_BIT_6_40_THEN_getRe_ETC__q6 =
	     (a__h2046 &
	      IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[0]) ?
	       9'd2 :
	       9'd0 ;
  assign IF_a046_XOR_IF_getResult_b_BIT_6_40_THEN_getRe_ETC__q16 =
	     (a__h2046 ^
	      IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[0]) ?
	       8'd1 :
	       8'd0 ;
  assign IF_a390_AND_IF_getResult_b_BIT_3_6_THEN_getRes_ETC__q3 =
	     (a__h3390 &
	      IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[0]) ?
	       9'd2 :
	       9'd0 ;
  assign IF_a390_XOR_IF_getResult_b_BIT_3_6_THEN_getRes_ETC__q8 =
	     (a__h3390 ^
	      IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[0]) ?
	       8'd1 :
	       8'd0 ;
  assign IF_a494_AND_IF_getResult_b_BIT_5_92_THEN_getRe_ETC__q5 =
	     (a__h2494 &
	      IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[0]) ?
	       9'd2 :
	       9'd0 ;
  assign IF_a494_XOR_IF_getResult_b_BIT_5_92_THEN_getRe_ETC__q13 =
	     (a__h2494 ^
	      IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[0]) ?
	       8'd1 :
	       8'd0 ;
  assign IF_a598_AND_IF_getResult_b_BIT_7_88_THEN_getRe_ETC__q7 =
	     (a__h1598 &
	      IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[0]) ?
	       9'd2 :
	       9'd0 ;
  assign IF_a598_XOR_IF_getResult_b_BIT_7_88_THEN_getRe_ETC__q15 =
	     (a__h1598 ^
	      IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[0]) ?
	       8'd1 :
	       8'd0 ;
  assign IF_a838_AND_IF_getResult_b_BIT_2_8_THEN_getRes_ETC__q2 =
	     (a__h3838 &
	      IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[0]) ?
	       9'd2 :
	       9'd0 ;
  assign IF_a838_XOR_IF_getResult_b_BIT_2_8_THEN_getRes_ETC__q9 =
	     (a__h3838 ^
	      IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[0]) ?
	       8'd1 :
	       8'd0 ;
  assign IF_a942_AND_IF_getResult_b_BIT_4_44_THEN_getRe_ETC__q4 =
	     (a__h2942 &
	      IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[0]) ?
	       9'd2 :
	       9'd0 ;
  assign IF_a942_XOR_IF_getResult_b_BIT_4_44_THEN_getRe_ETC__q14 =
	     (a__h2942 ^
	      IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[0]) ?
	       8'd1 :
	       8'd0 ;
  assign IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0_B_ETC___d343 =
	     { temp__h17465 ^ c__h17464,
	       temp__h17306 ^ c__h17305,
	       temp__h17146 ^
	       IF_a598_AND_IF_getResult_b_BIT_7_88_THEN_getRe_ETC__q7[1] } ;
  assign IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0_B_ETC___d344 =
	     { temp__h17783 ^ c__h17782,
	       temp__h17624 ^ c__h17623,
	       IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0_B_ETC___d343 } ;
  assign IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2 =
	     getResult_b[0] ? getResult_a : 8'd0 ;
  assign IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5 =
	     getResult_b[1] ? getResult_a : 8'd0 ;
  assign IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49 =
	     getResult_b[2] ? getResult_a : 8'd0 ;
  assign IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97 =
	     getResult_b[3] ? getResult_a : 8'd0 ;
  assign IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145 =
	     getResult_b[4] ? getResult_a : 8'd0 ;
  assign IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193 =
	     getResult_b[5] ? getResult_a : 8'd0 ;
  assign IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241 =
	     getResult_b[6] ? getResult_a : 8'd0 ;
  assign IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289 =
	     getResult_b[7] ? getResult_a : 8'd0 ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378 =
	     { {16{x__h1092[15]}}, x__h1092 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d604 =
	     { temp__h19358 ^
	       IF_SEXT_IF_getResult_b_BIT_0_THEN_getResult_a__ETC__q17[1],
	       IF_SEXT_IF_getResult_b_BIT_0_THEN_getResult_a__ETC__q18[0] } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d605 =
	     { temp__h19675 ^ c__h19674,
	       temp__h19517 ^ c__h19516,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d604 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d606 =
	     { temp__h19991 ^ c__h19990,
	       temp__h19833 ^ c__h19832,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d605 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d607 =
	     { temp__h20307 ^ c__h20306,
	       temp__h20149 ^ c__h20148,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d606 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d608 =
	     { temp__h20623 ^ c__h20622,
	       temp__h20465 ^ c__h20464,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d607 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d609 =
	     { temp__h20939 ^ c__h20938,
	       temp__h20781 ^ c__h20780,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d608 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d610 =
	     { temp__h21255 ^ c__h21254,
	       temp__h21097 ^ c__h21096,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d609 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d611 =
	     { temp__h21571 ^ c__h21570,
	       temp__h21413 ^ c__h21412,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d610 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d612 =
	     { temp__h21887 ^ c__h21886,
	       temp__h21729 ^ c__h21728,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d611 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d613 =
	     { temp__h22203 ^ c__h22202,
	       temp__h22045 ^ c__h22044,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d612 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d614 =
	     { temp__h22519 ^ c__h22518,
	       temp__h22361 ^ c__h22360,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d613 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d615 =
	     { temp__h22835 ^ c__h22834,
	       temp__h22677 ^ c__h22676,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d614 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d616 =
	     { temp__h23151 ^ c__h23150,
	       temp__h22993 ^ c__h22992,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d615 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d617 =
	     { temp__h23467 ^ c__h23466,
	       temp__h23309 ^ c__h23308,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d616 } ;
  assign SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d618 =
	     { temp__h23783 ^ c__h23782,
	       temp__h23625 ^ c__h23624,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d617 } ;
  assign _theResult___fst__h1098 =
	     { IF_a598_XOR_IF_getResult_b_BIT_7_88_THEN_getRe_ETC__q15[0],
	       IF_a046_XOR_IF_getResult_b_BIT_6_40_THEN_getRe_ETC__q16[0],
	       IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC___d375 } ;
  assign _theResult___fst__h65 =
	     { temp__h24099 ^ c__h24098,
	       temp__h23941 ^ c__h23940,
	       SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d618 } ;
  assign _theResult___snd__h1099 =
	     { x__h18115 | y__h18116, sum_BITS_7_TO_1___h18748 } ;
  assign a__h10139 = temp__h8551 ^ c__h8550 ;
  assign a__h10299 = temp__h8710 ^ c__h8709 ;
  assign a__h10458 = temp__h8869 ^ c__h8868 ;
  assign a__h10617 = temp__h9028 ^ c__h9027 ;
  assign a__h10776 = temp__h9187 ^ c__h9186 ;
  assign a__h10935 = temp__h9346 ^ c__h9345 ;
  assign a__h11094 = x__h9360 | y__h9361 ;
  assign a__h11890 = temp__h10302 ^ c__h10301 ;
  assign a__h12050 = temp__h10461 ^ c__h10460 ;
  assign a__h12209 = temp__h10620 ^ c__h10619 ;
  assign a__h12368 = temp__h10779 ^ c__h10778 ;
  assign a__h12527 = temp__h10938 ^ c__h10937 ;
  assign a__h12686 = temp__h11097 ^ c__h11096 ;
  assign a__h12845 = x__h11111 | y__h11112 ;
  assign a__h13641 = temp__h12053 ^ c__h12052 ;
  assign a__h13801 = temp__h12212 ^ c__h12211 ;
  assign a__h13960 = temp__h12371 ^ c__h12370 ;
  assign a__h14119 = temp__h12530 ^ c__h12529 ;
  assign a__h14278 = temp__h12689 ^ c__h12688 ;
  assign a__h14437 = temp__h12848 ^ c__h12847 ;
  assign a__h14596 = x__h12862 | y__h12863 ;
  assign a__h15392 = temp__h13804 ^ c__h13803 ;
  assign a__h15552 = temp__h13963 ^ c__h13962 ;
  assign a__h15711 = temp__h14122 ^ c__h14121 ;
  assign a__h15870 = temp__h14281 ^ c__h14280 ;
  assign a__h1598 =
	     temp__h15395 ^
	     IF_a046_AND_IF_getResult_b_BIT_6_40_THEN_getRe_ETC__q6[1] ;
  assign a__h16029 = temp__h14440 ^ c__h14439 ;
  assign a__h16188 = temp__h14599 ^ c__h14598 ;
  assign a__h16347 = x__h14613 | y__h14614 ;
  assign a__h17143 = temp__h15555 ^ c__h15554 ;
  assign a__h17303 = temp__h15714 ^ c__h15713 ;
  assign a__h17462 = temp__h15873 ^ c__h15872 ;
  assign a__h17621 = temp__h16032 ^ c__h16031 ;
  assign a__h17780 = temp__h16191 ^ c__h16190 ;
  assign a__h17939 = temp__h16350 ^ c__h16349 ;
  assign a__h18098 = x__h16364 | y__h16365 ;
  assign a__h2046 =
	     temp__h13644 ^
	     IF_a494_AND_IF_getResult_b_BIT_5_92_THEN_getRe_ETC__q5[1] ;
  assign a__h2494 =
	     temp__h11893 ^
	     IF_a942_AND_IF_getResult_b_BIT_4_44_THEN_getRe_ETC__q4[1] ;
  assign a__h2942 =
	     temp__h10142 ^
	     IF_a390_AND_IF_getResult_b_BIT_3_6_THEN_getRes_ETC__q3[1] ;
  assign a__h3390 =
	     temp__h8391 ^
	     IF_a838_AND_IF_getResult_b_BIT_2_8_THEN_getRes_ETC__q2[1] ;
  assign a__h3838 =
	     temp__h6640 ^
	     IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q1[1] ;
  assign a__h8388 = temp__h6800 ^ c__h6799 ;
  assign a__h8548 = temp__h6959 ^ c__h6958 ;
  assign a__h8707 = temp__h7118 ^ c__h7117 ;
  assign a__h8866 = temp__h7277 ^ c__h7276 ;
  assign a__h9025 = temp__h7436 ^ c__h7435 ;
  assign a__h9184 =
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[7] ^ c__h7594 ;
  assign a__h9343 =
	     c__h7594 & IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[7] ;
  assign c__h10301 = x__h10156 | y__h10157 ;
  assign c__h10460 = x__h10316 | y__h10317 ;
  assign c__h10619 = x__h10475 | y__h10476 ;
  assign c__h10778 = x__h10634 | y__h10635 ;
  assign c__h10937 = x__h10793 | y__h10794 ;
  assign c__h11096 = x__h10952 | y__h10953 ;
  assign c__h12052 = x__h11907 | y__h11908 ;
  assign c__h12211 = x__h12067 | y__h12068 ;
  assign c__h12370 = x__h12226 | y__h12227 ;
  assign c__h12529 = x__h12385 | y__h12386 ;
  assign c__h12688 = x__h12544 | y__h12545 ;
  assign c__h12847 = x__h12703 | y__h12704 ;
  assign c__h13803 = x__h13658 | y__h13659 ;
  assign c__h13962 = x__h13818 | y__h13819 ;
  assign c__h14121 = x__h13977 | y__h13978 ;
  assign c__h14280 = x__h14136 | y__h14137 ;
  assign c__h14439 = x__h14295 | y__h14296 ;
  assign c__h14598 = x__h14454 | y__h14455 ;
  assign c__h15554 = x__h15409 | y__h15410 ;
  assign c__h15713 = x__h15569 | y__h15570 ;
  assign c__h15872 = x__h15728 | y__h15729 ;
  assign c__h16031 = x__h15887 | y__h15888 ;
  assign c__h16190 = x__h16046 | y__h16047 ;
  assign c__h16349 = x__h16205 | y__h16206 ;
  assign c__h17305 = x__h17160 | y__h17161 ;
  assign c__h17464 = x__h17320 | y__h17321 ;
  assign c__h17623 = x__h17479 | y__h17480 ;
  assign c__h17782 = x__h17638 | y__h17639 ;
  assign c__h17941 = x__h17797 | y__h17798 ;
  assign c__h18100 = x__h17956 | y__h17957 ;
  assign c__h19516 = x__h19372 | y__h19373 ;
  assign c__h19674 = x__h19531 | y__h19532 ;
  assign c__h19832 = x__h19689 | y__h19690 ;
  assign c__h19990 = x__h19847 | y__h19848 ;
  assign c__h20148 = x__h20005 | y__h20006 ;
  assign c__h20306 = x__h20163 | y__h20164 ;
  assign c__h20464 = x__h20321 | y__h20322 ;
  assign c__h20622 = x__h20479 | y__h20480 ;
  assign c__h20780 = x__h20637 | y__h20638 ;
  assign c__h20938 = x__h20795 | y__h20796 ;
  assign c__h21096 = x__h20953 | y__h20954 ;
  assign c__h21254 = x__h21111 | y__h21112 ;
  assign c__h21412 = x__h21269 | y__h21270 ;
  assign c__h21570 = x__h21427 | y__h21428 ;
  assign c__h21728 = x__h21585 | y__h21586 ;
  assign c__h21886 = x__h21743 | y__h21744 ;
  assign c__h22044 = x__h21901 | y__h21902 ;
  assign c__h22202 = x__h22059 | y__h22060 ;
  assign c__h22360 = x__h22217 | y__h22218 ;
  assign c__h22518 = x__h22375 | y__h22376 ;
  assign c__h22676 = x__h22533 | y__h22534 ;
  assign c__h22834 = x__h22691 | y__h22692 ;
  assign c__h22992 = x__h22849 | y__h22850 ;
  assign c__h23150 = x__h23007 | y__h23008 ;
  assign c__h23308 = x__h23165 | y__h23166 ;
  assign c__h23466 = x__h23323 | y__h23324 ;
  assign c__h23624 = x__h23481 | y__h23482 ;
  assign c__h23782 = x__h23639 | y__h23640 ;
  assign c__h23940 = x__h23797 | y__h23798 ;
  assign c__h24098 = x__h23955 | y__h23956 ;
  assign c__h6799 = x__h6654 | y__h6655 ;
  assign c__h6958 = x__h6814 | y__h6815 ;
  assign c__h7117 = x__h6973 | y__h6974 ;
  assign c__h7276 = x__h7132 | y__h7133 ;
  assign c__h7435 = x__h7291 | y__h7292 ;
  assign c__h7594 = x__h7450 | y__h7451 ;
  assign c__h8550 = x__h8405 | y__h8406 ;
  assign c__h8709 = x__h8565 | y__h8566 ;
  assign c__h8868 = x__h8724 | y__h8725 ;
  assign c__h9027 = x__h8883 | y__h8884 ;
  assign c__h9186 = x__h9042 | y__h9043 ;
  assign c__h9345 = x__h9201 | y__h9202 ;
  assign sum_BITS_7_TO_1___h18748 =
	     { temp__h18101 ^ c__h18100,
	       temp__h17942 ^ c__h17941,
	       IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0_B_ETC___d344 } ;
  assign temp__h10142 =
	     a__h10139 ^
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[1] ;
  assign temp__h10302 =
	     a__h10299 ^
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[2] ;
  assign temp__h10461 =
	     a__h10458 ^
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[3] ;
  assign temp__h10620 =
	     a__h10617 ^
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[4] ;
  assign temp__h10779 =
	     a__h10776 ^
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[5] ;
  assign temp__h10938 =
	     a__h10935 ^
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[6] ;
  assign temp__h11097 =
	     a__h11094 ^
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[7] ;
  assign temp__h11893 =
	     a__h11890 ^
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[1] ;
  assign temp__h12053 =
	     a__h12050 ^
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[2] ;
  assign temp__h12212 =
	     a__h12209 ^
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[3] ;
  assign temp__h12371 =
	     a__h12368 ^
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[4] ;
  assign temp__h12530 =
	     a__h12527 ^
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[5] ;
  assign temp__h12689 =
	     a__h12686 ^
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[6] ;
  assign temp__h12848 =
	     a__h12845 ^
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[7] ;
  assign temp__h13644 =
	     a__h13641 ^
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[1] ;
  assign temp__h13804 =
	     a__h13801 ^
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[2] ;
  assign temp__h13963 =
	     a__h13960 ^
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[3] ;
  assign temp__h14122 =
	     a__h14119 ^
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[4] ;
  assign temp__h14281 =
	     a__h14278 ^
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[5] ;
  assign temp__h14440 =
	     a__h14437 ^
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[6] ;
  assign temp__h14599 =
	     a__h14596 ^
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[7] ;
  assign temp__h15395 =
	     a__h15392 ^
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[1] ;
  assign temp__h15555 =
	     a__h15552 ^
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[2] ;
  assign temp__h15714 =
	     a__h15711 ^
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[3] ;
  assign temp__h15873 =
	     a__h15870 ^
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[4] ;
  assign temp__h16032 =
	     a__h16029 ^
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[5] ;
  assign temp__h16191 =
	     a__h16188 ^
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[6] ;
  assign temp__h16350 =
	     a__h16347 ^
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[7] ;
  assign temp__h17146 =
	     a__h17143 ^
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[1] ;
  assign temp__h17306 =
	     a__h17303 ^
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[2] ;
  assign temp__h17465 =
	     a__h17462 ^
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[3] ;
  assign temp__h17624 =
	     a__h17621 ^
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[4] ;
  assign temp__h17783 =
	     a__h17780 ^
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[5] ;
  assign temp__h17942 =
	     a__h17939 ^
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[6] ;
  assign temp__h18101 =
	     a__h18098 ^
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[7] ;
  assign temp__h19358 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[1] ^
	     getResult_c[1] ;
  assign temp__h19517 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[2] ^
	     getResult_c[2] ;
  assign temp__h19675 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[3] ^
	     getResult_c[3] ;
  assign temp__h19833 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[4] ^
	     getResult_c[4] ;
  assign temp__h19991 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[5] ^
	     getResult_c[5] ;
  assign temp__h20149 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[6] ^
	     getResult_c[6] ;
  assign temp__h20307 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[7] ^
	     getResult_c[7] ;
  assign temp__h20465 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[8] ^
	     getResult_c[8] ;
  assign temp__h20623 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[9] ^
	     getResult_c[9] ;
  assign temp__h20781 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[10] ^
	     getResult_c[10] ;
  assign temp__h20939 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[11] ^
	     getResult_c[11] ;
  assign temp__h21097 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[12] ^
	     getResult_c[12] ;
  assign temp__h21255 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[13] ^
	     getResult_c[13] ;
  assign temp__h21413 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[14] ^
	     getResult_c[14] ;
  assign temp__h21571 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[15] ^
	     getResult_c[15] ;
  assign temp__h21729 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[16] ^
	     getResult_c[16] ;
  assign temp__h21887 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[17] ^
	     getResult_c[17] ;
  assign temp__h22045 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[18] ^
	     getResult_c[18] ;
  assign temp__h22203 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[19] ^
	     getResult_c[19] ;
  assign temp__h22361 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[20] ^
	     getResult_c[20] ;
  assign temp__h22519 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[21] ^
	     getResult_c[21] ;
  assign temp__h22677 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[22] ^
	     getResult_c[22] ;
  assign temp__h22835 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[23] ^
	     getResult_c[23] ;
  assign temp__h22993 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[24] ^
	     getResult_c[24] ;
  assign temp__h23151 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[25] ^
	     getResult_c[25] ;
  assign temp__h23309 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[26] ^
	     getResult_c[26] ;
  assign temp__h23467 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[27] ^
	     getResult_c[27] ;
  assign temp__h23625 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[28] ^
	     getResult_c[28] ;
  assign temp__h23783 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[29] ^
	     getResult_c[29] ;
  assign temp__h23941 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[30] ^
	     getResult_c[30] ;
  assign temp__h24099 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[31] ^
	     getResult_c[31] ;
  assign temp__h6640 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[2] ^
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[1] ;
  assign temp__h6800 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[3] ^
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[2] ;
  assign temp__h6959 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[4] ^
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[3] ;
  assign temp__h7118 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[5] ^
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[4] ;
  assign temp__h7277 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[6] ^
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[5] ;
  assign temp__h7436 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[7] ^
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[6] ;
  assign temp__h8391 =
	     a__h8388 ^
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[1] ;
  assign temp__h8551 =
	     a__h8548 ^
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[2] ;
  assign temp__h8710 =
	     a__h8707 ^
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[3] ;
  assign temp__h8869 =
	     a__h8866 ^
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[4] ;
  assign temp__h9028 =
	     a__h9025 ^
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[5] ;
  assign temp__h9187 =
	     a__h9184 ^
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[6] ;
  assign temp__h9346 =
	     a__h9343 ^
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[7] ;
  assign x__h10156 =
	     a__h10139 &
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[1] ;
  assign x__h10316 =
	     a__h10299 &
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[2] ;
  assign x__h10475 =
	     a__h10458 &
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[3] ;
  assign x__h10634 =
	     a__h10617 &
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[4] ;
  assign x__h10793 =
	     a__h10776 &
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[5] ;
  assign x__h1092 = { _theResult___snd__h1099, _theResult___fst__h1098 } ;
  assign x__h10952 =
	     a__h10935 &
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[6] ;
  assign x__h11111 =
	     a__h11094 &
	     IF_getResult_b_BIT_3_6_THEN_getResult_a_ELSE_0___d97[7] ;
  assign x__h11907 =
	     a__h11890 &
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[1] ;
  assign x__h12067 =
	     a__h12050 &
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[2] ;
  assign x__h12226 =
	     a__h12209 &
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[3] ;
  assign x__h12385 =
	     a__h12368 &
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[4] ;
  assign x__h12544 =
	     a__h12527 &
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[5] ;
  assign x__h12703 =
	     a__h12686 &
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[6] ;
  assign x__h12862 =
	     a__h12845 &
	     IF_getResult_b_BIT_4_44_THEN_getResult_a_ELSE_0___d145[7] ;
  assign x__h13658 =
	     a__h13641 &
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[1] ;
  assign x__h13818 =
	     a__h13801 &
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[2] ;
  assign x__h13977 =
	     a__h13960 &
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[3] ;
  assign x__h14136 =
	     a__h14119 &
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[4] ;
  assign x__h14295 =
	     a__h14278 &
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[5] ;
  assign x__h14454 =
	     a__h14437 &
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[6] ;
  assign x__h14613 =
	     a__h14596 &
	     IF_getResult_b_BIT_5_92_THEN_getResult_a_ELSE_0___d193[7] ;
  assign x__h15409 =
	     a__h15392 &
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[1] ;
  assign x__h15569 =
	     a__h15552 &
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[2] ;
  assign x__h15728 =
	     a__h15711 &
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[3] ;
  assign x__h15887 =
	     a__h15870 &
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[4] ;
  assign x__h16046 =
	     a__h16029 &
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[5] ;
  assign x__h16205 =
	     a__h16188 &
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[6] ;
  assign x__h16364 =
	     a__h16347 &
	     IF_getResult_b_BIT_6_40_THEN_getResult_a_ELSE_0___d241[7] ;
  assign x__h17160 =
	     a__h17143 &
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[1] ;
  assign x__h17320 =
	     a__h17303 &
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[2] ;
  assign x__h17479 =
	     a__h17462 &
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[3] ;
  assign x__h17638 =
	     a__h17621 &
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[4] ;
  assign x__h17797 =
	     a__h17780 &
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[5] ;
  assign x__h17956 =
	     a__h17939 &
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[6] ;
  assign x__h18115 =
	     a__h18098 &
	     IF_getResult_b_BIT_7_88_THEN_getResult_a_ELSE_0___d289[7] ;
  assign x__h19372 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[1] &
	     getResult_c[1] ;
  assign x__h19531 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[2] &
	     getResult_c[2] ;
  assign x__h19689 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[3] &
	     getResult_c[3] ;
  assign x__h19847 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[4] &
	     getResult_c[4] ;
  assign x__h20005 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[5] &
	     getResult_c[5] ;
  assign x__h20163 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[6] &
	     getResult_c[6] ;
  assign x__h20321 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[7] &
	     getResult_c[7] ;
  assign x__h20479 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[8] &
	     getResult_c[8] ;
  assign x__h20637 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[9] &
	     getResult_c[9] ;
  assign x__h20795 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[10] &
	     getResult_c[10] ;
  assign x__h20953 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[11] &
	     getResult_c[11] ;
  assign x__h21111 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[12] &
	     getResult_c[12] ;
  assign x__h21269 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[13] &
	     getResult_c[13] ;
  assign x__h21427 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[14] &
	     getResult_c[14] ;
  assign x__h21585 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[15] &
	     getResult_c[15] ;
  assign x__h21743 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[16] &
	     getResult_c[16] ;
  assign x__h21901 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[17] &
	     getResult_c[17] ;
  assign x__h22059 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[18] &
	     getResult_c[18] ;
  assign x__h22217 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[19] &
	     getResult_c[19] ;
  assign x__h22375 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[20] &
	     getResult_c[20] ;
  assign x__h22533 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[21] &
	     getResult_c[21] ;
  assign x__h22691 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[22] &
	     getResult_c[22] ;
  assign x__h22849 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[23] &
	     getResult_c[23] ;
  assign x__h23007 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[24] &
	     getResult_c[24] ;
  assign x__h23165 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[25] &
	     getResult_c[25] ;
  assign x__h23323 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[26] &
	     getResult_c[26] ;
  assign x__h23481 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[27] &
	     getResult_c[27] ;
  assign x__h23639 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[28] &
	     getResult_c[28] ;
  assign x__h23797 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[29] &
	     getResult_c[29] ;
  assign x__h23955 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[30] &
	     getResult_c[30] ;
  assign x__h24113 =
	     SEXT_IF_getResult_b_BIT_0_THEN_getResult_a_ELS_ETC___d378[31] &
	     getResult_c[31] ;
  assign x__h6654 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[2] &
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[1] ;
  assign x__h6814 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[3] &
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[2] ;
  assign x__h6973 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[4] &
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[3] ;
  assign x__h7132 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[5] &
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[4] ;
  assign x__h7291 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[6] &
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[5] ;
  assign x__h7450 =
	     IF_getResult_b_BIT_0_THEN_getResult_a_ELSE_0___d2[7] &
	     IF_getResult_b_BIT_1_THEN_getResult_a_ELSE_0___d5[6] ;
  assign x__h8405 =
	     a__h8388 &
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[1] ;
  assign x__h8565 =
	     a__h8548 &
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[2] ;
  assign x__h8724 =
	     a__h8707 &
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[3] ;
  assign x__h8883 =
	     a__h8866 &
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[4] ;
  assign x__h9042 =
	     a__h9025 &
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[5] ;
  assign x__h9201 =
	     a__h9184 &
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[6] ;
  assign x__h9360 =
	     a__h9343 &
	     IF_getResult_b_BIT_2_8_THEN_getResult_a_ELSE_0___d49[7] ;
  assign y__h10157 =
	     IF_a390_AND_IF_getResult_b_BIT_3_6_THEN_getRes_ETC__q3[1] &
	     temp__h10142 ;
  assign y__h10317 = c__h10301 & temp__h10302 ;
  assign y__h10476 = c__h10460 & temp__h10461 ;
  assign y__h10635 = c__h10619 & temp__h10620 ;
  assign y__h10794 = c__h10778 & temp__h10779 ;
  assign y__h10953 = c__h10937 & temp__h10938 ;
  assign y__h11112 = c__h11096 & temp__h11097 ;
  assign y__h11908 =
	     IF_a942_AND_IF_getResult_b_BIT_4_44_THEN_getRe_ETC__q4[1] &
	     temp__h11893 ;
  assign y__h12068 = c__h12052 & temp__h12053 ;
  assign y__h12227 = c__h12211 & temp__h12212 ;
  assign y__h12386 = c__h12370 & temp__h12371 ;
  assign y__h12545 = c__h12529 & temp__h12530 ;
  assign y__h12704 = c__h12688 & temp__h12689 ;
  assign y__h12863 = c__h12847 & temp__h12848 ;
  assign y__h13659 =
	     IF_a494_AND_IF_getResult_b_BIT_5_92_THEN_getRe_ETC__q5[1] &
	     temp__h13644 ;
  assign y__h13819 = c__h13803 & temp__h13804 ;
  assign y__h13978 = c__h13962 & temp__h13963 ;
  assign y__h14137 = c__h14121 & temp__h14122 ;
  assign y__h14296 = c__h14280 & temp__h14281 ;
  assign y__h14455 = c__h14439 & temp__h14440 ;
  assign y__h14614 = c__h14598 & temp__h14599 ;
  assign y__h15410 =
	     IF_a046_AND_IF_getResult_b_BIT_6_40_THEN_getRe_ETC__q6[1] &
	     temp__h15395 ;
  assign y__h15570 = c__h15554 & temp__h15555 ;
  assign y__h15729 = c__h15713 & temp__h15714 ;
  assign y__h15888 = c__h15872 & temp__h15873 ;
  assign y__h16047 = c__h16031 & temp__h16032 ;
  assign y__h16206 = c__h16190 & temp__h16191 ;
  assign y__h16365 = c__h16349 & temp__h16350 ;
  assign y__h17161 =
	     IF_a598_AND_IF_getResult_b_BIT_7_88_THEN_getRe_ETC__q7[1] &
	     temp__h17146 ;
  assign y__h17321 = c__h17305 & temp__h17306 ;
  assign y__h17480 = c__h17464 & temp__h17465 ;
  assign y__h17639 = c__h17623 & temp__h17624 ;
  assign y__h17798 = c__h17782 & temp__h17783 ;
  assign y__h17957 = c__h17941 & temp__h17942 ;
  assign y__h18116 = c__h18100 & temp__h18101 ;
  assign y__h19373 =
	     IF_SEXT_IF_getResult_b_BIT_0_THEN_getResult_a__ETC__q17[1] &
	     temp__h19358 ;
  assign y__h19532 = c__h19516 & temp__h19517 ;
  assign y__h19690 = c__h19674 & temp__h19675 ;
  assign y__h19848 = c__h19832 & temp__h19833 ;
  assign y__h20006 = c__h19990 & temp__h19991 ;
  assign y__h20164 = c__h20148 & temp__h20149 ;
  assign y__h20322 = c__h20306 & temp__h20307 ;
  assign y__h20480 = c__h20464 & temp__h20465 ;
  assign y__h20638 = c__h20622 & temp__h20623 ;
  assign y__h20796 = c__h20780 & temp__h20781 ;
  assign y__h20954 = c__h20938 & temp__h20939 ;
  assign y__h21112 = c__h21096 & temp__h21097 ;
  assign y__h21270 = c__h21254 & temp__h21255 ;
  assign y__h21428 = c__h21412 & temp__h21413 ;
  assign y__h21586 = c__h21570 & temp__h21571 ;
  assign y__h21744 = c__h21728 & temp__h21729 ;
  assign y__h21902 = c__h21886 & temp__h21887 ;
  assign y__h22060 = c__h22044 & temp__h22045 ;
  assign y__h22218 = c__h22202 & temp__h22203 ;
  assign y__h22376 = c__h22360 & temp__h22361 ;
  assign y__h22534 = c__h22518 & temp__h22519 ;
  assign y__h22692 = c__h22676 & temp__h22677 ;
  assign y__h22850 = c__h22834 & temp__h22835 ;
  assign y__h23008 = c__h22992 & temp__h22993 ;
  assign y__h23166 = c__h23150 & temp__h23151 ;
  assign y__h23324 = c__h23308 & temp__h23309 ;
  assign y__h23482 = c__h23466 & temp__h23467 ;
  assign y__h23640 = c__h23624 & temp__h23625 ;
  assign y__h23798 = c__h23782 & temp__h23783 ;
  assign y__h23956 = c__h23940 & temp__h23941 ;
  assign y__h24114 = c__h24098 & temp__h24099 ;
  assign y__h6655 =
	     IF_IF_getResult_b_BIT_0_THEN_getResult_a_ELSE__ETC__q1[1] &
	     temp__h6640 ;
  assign y__h6815 = c__h6799 & temp__h6800 ;
  assign y__h6974 = c__h6958 & temp__h6959 ;
  assign y__h7133 = c__h7117 & temp__h7118 ;
  assign y__h7292 = c__h7276 & temp__h7277 ;
  assign y__h7451 = c__h7435 & temp__h7436 ;
  assign y__h8406 =
	     IF_a838_AND_IF_getResult_b_BIT_2_8_THEN_getRes_ETC__q2[1] &
	     temp__h8391 ;
  assign y__h8566 = c__h8550 & temp__h8551 ;
  assign y__h8725 = c__h8709 & temp__h8710 ;
  assign y__h8884 = c__h8868 & temp__h8869 ;
  assign y__h9043 = c__h9027 & temp__h9028 ;
  assign y__h9202 = c__h9186 & temp__h9187 ;
  assign y__h9361 = c__h9345 & temp__h9346 ;
endmodule  // mac_wrap

